TableSkill = TableSkill or { 
[2011] = { ["Name"] = [[翔云]], ["Type"] = 1, ["Distance"] = 60, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 30, ["Moves"] = {[5]={frames=25,x=0,y=300}}, ["Actions"] = {[1]="Skill2"}, ["CDFrames"] = 180, ["Impacks"] = {[10]={6}}, ["AfterScript"] = [[Skill2011_After]], ["Description"] = [[运用自身内力发出的招式，可以破除敌人防御。]]},
[2012] = { ["Name"] = [[破罡正气]], ["Type"] = 1, ["Distance"] = 80, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 53, ["Moves"] = {}, ["Actions"] = {[1]="Skill1"}, ["CDFrames"] = 240, ["Impacks"] = {[30]={1}}, ["Description"] = [[普通攻击]]},
[3011] = { ["Name"] = [[剑道]], ["Type"] = 1, ["Distance"] = 60, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 35, ["Moves"] = {}, ["Actions"] = {[1]="Skill2"}, ["CDFrames"] = 180, ["Impacks"] = {[15]={7}}, ["Description"] = [[强烈的剑气给予敌人重击。]]},
[3012] = { ["Name"] = [[剑气怒斩]], ["Type"] = 1, ["Distance"] = 60, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 24, ["Moves"] = {}, ["Actions"] = {[1]="Skill1"}, ["CDFrames"] = 120, ["Impacks"] = {[15]={5}}, ["Description"] = [[普通攻击]]},
[4011] = { ["Name"] = [[蝶舞]], ["Type"] = 1, ["Distance"] = 300, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 51, ["Moves"] = {}, ["Actions"] = {[1]="Skill2"}, ["CDFrames"] = 180, ["Impacks"] = {}, ["Description"] = [[变化多端，难于防御。]]},
[4012] = { ["Name"] = [[飞云丝带]], ["Type"] = 1, ["Distance"] = 300, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 51, ["Moves"] = {}, ["Actions"] = {[1]="Skill1"}, ["CDFrames"] = 300, ["Impacks"] = {[30]={4}}, ["Description"] = [[普通攻击]]},
[5011] = { ["Name"] = [[岩柱]], ["Type"] = 1, ["Distance"] = 200, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 45, ["Moves"] = {}, ["Actions"] = {[1]="Skill2"}, ["CDFrames"] = 180, ["Impacks"] = {}, ["Description"] = [[对前方范围内敌人强力的猛击。]]},
[5012] = { ["Name"] = [[爆烈之炎]], ["Type"] = 1, ["Distance"] = 80, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 45, ["Moves"] = {[10]={frames=35,x=20,y=0}}, ["Actions"] = {[1]="Skill1"}, ["CDFrames"] = 180, ["Impacks"] = {[25]={3}}, ["Description"] = [[普通攻击]]},
[6011] = { ["Name"] = [[魅影]], ["Type"] = 1, ["Distance"] = 200, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 44, ["Moves"] = {}, ["Actions"] = {[1]="Skill2"}, ["CDFrames"] = 180, ["Impacks"] = {}, ["Description"] = [[通过扇子发出攻击。]]},
[6012] = { ["Name"] = [[轮回之环]], ["Type"] = 1, ["Distance"] = 100, ["CastFrames"] = 0, ["CastMoves"] = {}, ["CastActions"] = {}, ["Frames"] = 44, ["Moves"] = {}, ["Actions"] = {[1]="Skill1"}, ["CDFrames"] = 120, ["Impacks"] = {[20]={2}}, ["Description"] = [[普通攻击]]}
}